### ISSUE TITLE
Bug in detector gui element

### ISSUE THREAD

**Issue by 0b11001111** [pyhmsa/pyhmsa-gui#1]
I'm not able to display a detector condition in the viewer which seems to be caused by an incompatibility to qt5. I attached the full log to this issue.

[log.txt](https://github.com/pyhmsa/pyhmsa-gui/files/464013/log.txt)

**Comment by ppinard** [comment]
Can you please check if this error occurs in the _development_ branch?

**Comment by 0b11001111** [comment]
I did and anything works fine now. Thank you.
